packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  workerd: true
  '@tailwindcss/oxide': true
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20261001.1'
  - '@cloudflare/workerd-darwin-arm64@1.20261001.1'
  - '@cloudflare/workerd-linux-64@1.20261001.1'
  - '@cloudflare/workerd-linux-arm64@1.20261001.1'
  - '@cloudflare/workerd-windows-64@1.20261001.1'
  - miniflare@5.20261001.0-alpha
  - vite@8.3.2
  - workerd@1.20261001.1
  - wrangler@4.146.0
