import { Plus } from 'lucide-react';
import { resizePlan, type PlanInput, type CostCategory } from '@eddias/core';
import { Amount, categories, MonthlyGrid } from './fields';
export function Premises({ p, change }: { p: PlanInput; change: (v: PlanInput) => void }) {
  function updateChannel(i: number, fields: Partial<PlanInput['channels'][number]>) { change({ ...p, channels: p.channels.map((v, j) => j === i ? { ...v, ...fields } : v) }); }
  function updateCost(i: number, fields: Partial<PlanInput['costs'][number]>) { change({ ...p, costs: p.costs.map((v, j) => j === i ? { ...v, ...fields } : v) }); }
  return <><div className="form-grid"><label>Mês inicial<input type="month" required value={p.start_month.slice(0, 7)} min="2000-01" max="2099-12" onChange={e => { if (e.target.value) change({ ...p, start_month: e.target.value + '-01' }); }} /></label>
    <label>Meses de projeção<select value={p.months} onChange={e => change(resizePlan(p, Number(e.target.value)))}>{[3, 6, 12, 18, 24].map(n => <option key={n} value={n}>{n} meses</option>)}</select></label>
    <label>Saldo inicial do grupo (R$)<Amount value={p.opening_cents} optional signed label="Saldo inicial do grupo (R$)" onChange={n => change({ ...p, opening_cents: n })} /><small>Saldo imediatamente antes do mês inicial. Não somamos contas com datas diferentes.</small></label>
    <label>Fornecedores estimados (% do GMV)<input aria-label="Fornecedores estimados (% do GMV)" type="number" required min="0" max="100" step="0.01" value={p.supplier_bps / 100} onChange={e => change({ ...p, supplier_bps: Math.round(Number(e.target.value) * 100) })} /><small>Por mês: maior valor entre esta estimativa e os fornecedores já previstos.</small></label>
    <label>Impostos estimados (% do GMV)<input aria-label="Impostos estimados (% do GMV)" type="number" required min="0" max="100" step="0.01" value={p.tax_bps / 100} onChange={e => change({ ...p, tax_bps: Math.round(Number(e.target.value) * 100) })} /><small>Não inclua taxas já descontadas no percentual líquido dos repasses.</small></label></div>
    <div className="section-heading"><div><h2>Vendas e repasses por canal</h2><p>Quanto pretende faturar e qual parte chegará ao banco.</p></div><button type="button" className="secondary" onClick={() => change({ ...p, channels: [...p.channels, { id: crypto.randomUUID(), name: 'Novo canal', net_bps: 0, lag_days: 0, gmv_cents: Array(p.months).fill(0) }] })}><Plus size={16} />Adicionar canal</button></div>
    {p.channels.map((c, i) => <section className="premise-row" key={c.id}><div className="form-grid"><label>Nome do canal<input required maxLength={120} value={c.name} onChange={e => updateChannel(i, { name: e.target.value })} /></label>
      <label>Quanto entra na conta (%)<input aria-label={'Percentual líquido ' + c.name} type="number" min="0" max="100" step="0.01" required value={c.net_bps / 100} onChange={e => updateChannel(i, { net_bps: Math.round(Number(e.target.value) * 100) })} /></label>
      <label>Prazo médio de repasse (dias corridos)<input aria-label={'Prazo ' + c.name} type="number" min="0" max="180" step="1" required value={c.lag_days} onChange={e => updateChannel(i, { lag_days: Number(e.target.value) })} /></label>
      <div className="actions"><button type="button" className="secondary" onClick={() => updateChannel(i, { gmv_cents: Array(p.months).fill(c.gmv_cents[0]) })}>Repetir GMV do primeiro mês</button><button type="button" className="secondary" onClick={() => { if (window.confirm('Retirar esta premissa do cenário? Isso não altera vendas ou movimentos bancários.')) change({ ...p, channels: p.channels.filter((_, j) => j !== i) }); }}>Retirar canal do cenário</button></div></div>
      <MonthlyGrid p={p} name={c.name} amounts={c.gmv_cents} change={a => updateChannel(i, { gmv_cents: a })} /></section>)}
    <div className="section-heading"><div><h2>Custos e despesas recorrentes</h2><p>Premissas exclusivas deste cenário. Não repita valores já cadastrados em lançamentos.</p></div><button type="button" className="secondary" onClick={() => change({ ...p, costs: [...p.costs, { id: crypto.randomUUID(), name: 'Novo custo', category: 'fixos', amounts: Array(p.months).fill(0) }] })}><Plus size={16} />Adicionar custo</button></div>
    {p.costs.map((c, i) => <section className="premise-row" key={c.id}><div className="form-grid"><label>Descrição do custo<input required maxLength={120} value={c.name} onChange={e => updateCost(i, { name: e.target.value })} /></label>
      <label>Categoria<select value={c.category} onChange={e => updateCost(i, { category: e.target.value as CostCategory })}>{Object.entries(categories).map(([k, label]) => <option value={k} key={k}>{label}</option>)}</select></label></div>
      <MonthlyGrid p={p} name={c.name} amounts={c.amounts} change={a => updateCost(i, { amounts: a })} /><div className="actions"><button type="button" className="secondary" onClick={() => updateCost(i, { amounts: Array(p.months).fill(c.amounts[0]) })}>Repetir custo do primeiro mês</button><button type="button" className="secondary" onClick={() => { if (window.confirm('Retirar esta premissa do cenário?')) change({ ...p, costs: p.costs.filter((_, j) => j !== i) }); }}>Retirar custo do cenário</button></div></section>)}
    <label>Observações das premissas<textarea maxLength={4000} rows={3} value={p.notes} onChange={e => change({ ...p, notes: e.target.value })} /></label></>;
}
